# Generated by Django 3.1.4 on 2020-12-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categori',
            old_name='url',
            new_name='slug',
        ),
    ]
