# Generated by Django 3.1.4 on 2020-12-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0002_auto_20201218_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomDokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_document', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название документа')),
                ('filedom', models.FileField(upload_to='dom/dokument', verbose_name='Загрузить')),
                ('datepub', models.DateTimeField(auto_now_add=True, verbose_name='Дата копии')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
