# Generated by Django 3.1.4 on 2020-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0003_domdokument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField(unique=True, verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Артикулы',
                'ordering': ('-art',),
            },
        ),
    ]
