# Generated by Django 3.1.4 on 2020-12-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0006_domdokument_art_dokument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_krai', models.CharField(max_length=128, verbose_name='Край, область')),
                ('gorod', models.CharField(max_length=128, verbose_name='Нас. пункт')),
                ('raion', models.CharField(max_length=128, verbose_name='Район')),
                ('street', models.CharField(max_length=128, verbose_name='Улица')),
                ('arti_dokument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dom.articul', verbose_name='artic')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
