# Generated by Django 3.1.4 on 2020-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0008_auto_20201219_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='descreption',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='adres',
            name='is_arenda',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='В аренду'),
        ),
    ]
