# Generated by Django 3.1.4 on 2020-12-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0009_auto_20201219_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
