# Generated by Django 3.1.4 on 2020-12-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0010_adres_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articul',
            name='kod_phone',
            field=models.CharField(blank=True, help_text='Пятизначное число', max_length=3, null=True, verbose_name='Код телефона'),
        ),
        migrations.AddField(
            model_name='articul',
            name='mesto',
            field=models.CharField(blank=True, help_text='Двухзначное число', max_length=3, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='articul',
            name='nomer',
            field=models.CharField(blank=True, help_text='Шестизначное число', max_length=3, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='articul',
            name='region',
            field=models.CharField(blank=True, help_text='Трехзначное число', max_length=3, null=True, verbose_name='Код региона'),
        ),
        migrations.AddField(
            model_name='articul',
            name='slug',
            field=models.SlugField(blank=True, max_length=16, null=True, unique=True, verbose_name='Уникальная ссылка'),
        ),
    ]
