# Generated by Django 3.1.4 on 2020-12-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0011_auto_20201219_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='n_doma',
            field=models.CharField(default=0, max_length=10, verbose_name='№ дома'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='kod_phone',
            field=models.CharField(blank=True, help_text='Пятизначное число', max_length=5, null=True, verbose_name='Код телефона'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='mesto',
            field=models.CharField(blank=True, help_text='Двухзначное число', max_length=2, null=True, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='nomer',
            field=models.CharField(blank=True, default='000000', help_text='Шестизначное число', max_length=6, null=True, verbose_name='Порядковый номер'),
        ),
    ]
