# Generated by Django 3.1.4 on 2020-12-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0012_auto_20201220_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articul',
            name='art',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='region',
            field=models.CharField(blank=True, help_text='Трехзначное число - Краснодарский край 023 или 123 ', max_length=3, null=True, verbose_name='Код региона'),
        ),
    ]
