# Generated by Django 3.1.4 on 2021-01-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0013_auto_20201229_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='categorii',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dom.categori', verbose_name='categor'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='art',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='slug',
            field=models.SlugField(blank=True, max_length=19, null=True, unique=True, verbose_name='Уникальная ссылка'),
        ),
    ]
