# Generated by Django 3.1.4 on 2021-01-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0014_auto_20210104_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=500, null=True, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('status', models.CharField(choices=[('Pro', 'Продавец'), ('Poc', 'Покупатель'), ('No', 'Неизвестно'), ('Uri', 'Юрист'), ('Pom', 'Помошник')], default='No', max_length=300)),
                ('zadachi', models.DateField(blank=True, null=True, verbose_name='Дата задачи')),
                ('ispolneno', models.BooleanField(default=False, verbose_name='Исполнено')),
                ('nado', models.BooleanField(default=False, verbose_name='В работе')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AlterField(
            model_name='adres',
            name='arti_dokument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dom.articul', verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='categorii',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dom.categori', verbose_name='Категория земель'),
        ),
    ]
