# Generated by Django 3.1.4 on 2021-01-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0017_adres_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='famili',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ФИО'),
        ),
    ]
