# Generated by Django 3.1.4 on 2021-01-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0019_auto_20210104_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adres',
            name='prof',
        ),
        migrations.AddField(
            model_name='person',
            name='adres',
            field=models.ManyToManyField(to='dom.Adres'),
        ),
    ]
