# Generated by Django 3.1.4 on 2021-01-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0022_auto_20210104_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='categori',
            name='art_categori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dom.articul', verbose_name='Арт_категории'),
        ),
        migrations.AlterField(
            model_name='domdokument',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Pro', 'Продавец'), ('Poc', 'Покупатель'), ('No', 'Неизвестно'), ('Uri', 'Юрист'), ('Pom', 'Помошник')], default='No', max_length=300, verbose_name='Статус'),
        ),
    ]
