# Generated by Django 3.1.4 on 2021-02-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0024_fotodom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adres',
            options={'default_related_name': 'ad_res', 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterField(
            model_name='adres',
            name='arti_dokument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_res', to='dom.articul', verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='categorii',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_res', to='dom.categori', verbose_name='Категория земель'),
        ),
    ]
