# Generated by Django 3.1.4 on 2021-02-16 10:41

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('dom', '0026_articul_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='price',
            field=models.CharField(default='?', max_length=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
    ]
