# Generated by Django 3.1.4 on 2021-02-16 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('dom', '0027_auto_20210216_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adres',
            name='n_doma',
            field=models.CharField(default='', max_length=10, verbose_name='№ дома'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='price',
            field=models.CharField(default='?', max_length=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
    ]
