# Generated by Django 3.1.4 on 2021-02-18 11:31

from django.db import migrations, models
import dom.models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0028_auto_20210216_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='minimage',
            field=models.ImageField(blank=True, upload_to=dom.models.Adres.new_path, verbose_name='Миниатюра'),
        ),
    ]
