# Generated by Django 3.1.4 on 2021-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0030_auto_20210218_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='minimage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, verbose_name='Ссылка'),
        ),
    ]
