# Generated by Django 3.1 on 2021-02-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0032_remove_adres_minimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='minimage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Миниатюра'),
        ),
    ]
