# Generated by Django 3.1 on 2021-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20210219_0855'),
        ('dom', '0033_adres_minimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='uslugi_partnerov',
            field=models.ManyToManyField(blank=True, related_name='adress', to='partner.Usluga'),
        ),
    ]
