# Generated by Django 3.1 on 2021-02-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20210219_0855'),
        ('dom', '0034_adres_uslugi_partnerov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adres',
            name='uslugi_partnerov',
        ),
        migrations.AddField(
            model_name='adres',
            name='uslugi_partnerov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adress', to='partner.usluga'),
        ),
    ]
