# Generated by Django 3.1.4 on 2021-02-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28, verbose_name='Тема')),
                ('image', models.ImageField(blank=True, null=True, upload_to='urokipy/images', verbose_name='Картинка')),
                ('alt', models.CharField(blank=True, max_length=50, null=True, verbose_name='alt')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('links', models.URLField(default='#', verbose_name='Ссылка')),
                ('button_text', models.CharField(max_length=28, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Памятка',
                'verbose_name_plural': 'Памятки',
            },
        ),
    ]
