# Generated by Django 3.1.4 on 2021-02-15 09:32

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('urokipy', '0002_auto_20210214_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='karta',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
