# Generated by Django 3.1.4 on 2021-02-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urokipy', '0003_karta_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulma',
            fields=[
                ('karta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='urokipy.karta')),
            ],
            options={
                'verbose_name': 'Карточка bulma',
                'verbose_name_plural': 'Памятки bulma',
            },
            bases=('urokipy.karta',),
        ),
    ]
