# Generated by Django 3.1 on 2021-02-19 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorodok', models.CharField(blank=True, max_length=60, verbose_name='Населенный пункт')),
                ('vid_uslugi', models.CharField(default='Отсутствует', help_text='Укажите название услуги', max_length=96, verbose_name='Вид услуги')),
                ('kontakt', models.CharField(default='Укажите название услуги', max_length=12, verbose_name='Телефон')),
                ('nameurl', models.CharField(default='Имя ссылки', max_length=96, verbose_name='Название ссылки')),
                ('usluga_url', models.URLField(default='Ссылка отсутствует', verbose_name='Ссылка')),
                ('price', models.CharField(blank=True, max_length=18, verbose_name='Стоиммость')),
                ('ispolnitel', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
