# Generated by Django 3.1 on 2021-02-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluga',
            name='kontakt',
            field=models.CharField(default='Контактный номер телефона', max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='price',
            field=models.CharField(blank=True, default='Стоимость зависит от сложности договора', max_length=18, verbose_name='Стоиммость'),
        ),
    ]
