# Generated by Django 3.1 on 2021-02-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20210219_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluga',
            name='price',
            field=models.CharField(blank=True, default='Стоимость зависит от сложности договора', max_length=48, verbose_name='Стоимость'),
        ),
    ]
